# Generated by Django 5.2.7 on 2025-10-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(choices=[('admin_global', 'Administrador Global'), ('diretoria', 'Diretoria'), ('coordenador', 'Coordenador'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('aluno', 'Aluno')], max_length=20),
        ),
    ]
