# Generated by Django 5.2.7 on 2025-10-27 18:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('usuarios', '0002_alter_perfilusuario_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=20, null=True)),
                ('uf_rg', models.CharField(blank=True, max_length=2, null=True)),
                ('data_emissao_rg', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('formacao_academica', models.CharField(blank=True, max_length=200, null=True)),
                ('nivel_superior', models.BooleanField(default=False)),
                ('pos_graduacao', models.CharField(blank=True, max_length=200, null=True)),
                ('curso_formacao', models.CharField(blank=True, max_length=150, null=True)),
                ('instituicao_formacao', models.CharField(blank=True, max_length=150, null=True)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='core.polo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='usuarios.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('turno', models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Integral', 'Integral')], default='Manhã', max_length=10)),
                ('ano', models.IntegerField(default=datetime.datetime.now)),
                ('ano_letivo', models.IntegerField(default=2025)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.polo')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cor_raca', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10)),
                ('nacionalidade', models.CharField(blank=True, max_length=50)),
                ('estado_nascimento', models.CharField(blank=True, max_length=2)),
                ('municipio_nascimento', models.CharField(blank=True, max_length=100)),
                ('tipo_deficiencia', models.CharField(blank=True, max_length=100)),
                ('alergia_alimentar', models.BooleanField(default=False)),
                ('descricao_alergia', models.CharField(blank=True, max_length=200)),
                ('rg', models.CharField(blank=True, max_length=30, verbose_name='Nº da Identidade')),
                ('complemento_rg', models.CharField(blank=True, max_length=50)),
                ('orgao_emissor', models.CharField(blank=True, max_length=20)),
                ('uf_rg', models.CharField(blank=True, max_length=2)),
                ('data_expedicao_rg', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14)),
                ('nis', models.CharField(blank=True, max_length=20)),
                ('cartao_sus', models.CharField(blank=True, max_length=20)),
                ('bolsa_familia', models.BooleanField(default=False)),
                ('origem_quilombola', models.BooleanField(default=False)),
                ('tipo_certidao', models.CharField(blank=True, choices=[('Nascimento', 'Nascimento'), ('Casamento', 'Casamento')], max_length=20)),
                ('numero_termo', models.CharField(blank=True, max_length=30)),
                ('numero_livro', models.CharField(blank=True, max_length=30)),
                ('numero_folha', models.CharField(blank=True, max_length=30)),
                ('uf_certidao', models.CharField(blank=True, max_length=2)),
                ('data_emissao_certidao', models.DateField(blank=True, null=True)),
                ('municipio_cartorio', models.CharField(blank=True, max_length=100)),
                ('nome_cartorio', models.CharField(blank=True, max_length=100)),
                ('numero_certidao_nova', models.CharField(blank=True, max_length=60)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('uf_endereco', models.CharField(blank=True, max_length=2)),
                ('transporte_escolar', models.BooleanField(default=False)),
                ('tipo_veiculo', models.CharField(blank=True, max_length=50)),
                ('nome_mae', models.CharField(blank=True, max_length=150)),
                ('contato_mae', models.CharField(blank=True, max_length=20)),
                ('rg_mae', models.CharField(blank=True, max_length=30)),
                ('estado_rg_mae', models.CharField(blank=True, max_length=2)),
                ('data_emissao_rg_mae', models.DateField(blank=True, null=True)),
                ('orgao_emissor_mae', models.CharField(blank=True, max_length=20)),
                ('cpf_mae', models.CharField(blank=True, max_length=14)),
                ('nome_pai', models.CharField(blank=True, max_length=150)),
                ('contato_pai', models.CharField(blank=True, max_length=20)),
                ('rg_pai', models.CharField(blank=True, max_length=30)),
                ('estado_rg_pai', models.CharField(blank=True, max_length=2)),
                ('data_emissao_rg_pai', models.DateField(blank=True, null=True)),
                ('orgao_emissor_pai', models.CharField(blank=True, max_length=20)),
                ('cpf_pai', models.CharField(blank=True, max_length=14)),
                ('data_matricula', models.DateField(blank=True, null=True)),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='core.polo')),
                ('turma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.turma')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.AddConstraint(
            model_name='turma',
            constraint=models.UniqueConstraint(fields=('nome', 'ano', 'ano_letivo', 'polo'), name='unique_turma_por_polo'),
        ),
    ]
