# Generated by Django 5.2.7 on 2025-11-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0002_disciplina_turmaprofessordisciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('tipo', models.CharField(choices=[('normal', 'Dia Normal'), ('letivo', 'Dia Letivo / Aulas'), ('feriado', 'Feriado'), ('sabado_letivo', 'Sábado Letivo'), ('avaliacao', 'Dia de Avaliação'), ('reuniao', 'Reunião Pedagógica'), ('eventos', 'Eventos da Escola')], default='normal', max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_turma', to='escolas.turma'),
        ),
    ]
