# Generated by Django 5.2.7 on 2025-11-06 22:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('escolas', '0004_alter_disciplina_nome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('simulado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=4)),
                ('recuperacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bimestre', models.CharField(choices=[('1º', '1º'), ('2º', '2º'), ('3º', '3º')], max_length=10)),
                ('media_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('status', models.CharField(default='Em andamento', max_length=20)),
                ('cargo_lancou', models.CharField(blank=True, max_length=30, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='escolas.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.disciplina')),
                ('polo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='core.polo')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escolas.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.turma')),
                ('usuario_lancou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('aluno', 'disciplina', 'turma', 'bimestre', 'polo')},
            },
        ),
    ]
