# Generated by Django 5.2.7 on 2025-11-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0005_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_rg_mae',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_rg_pai',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
