# Generated by Django 5.2.7 on 2025-11-06 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0006_alter_aluno_estado_rg_mae_alter_aluno_estado_rg_pai'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolas.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escolas.aluno')),
                ('aula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencias', to='escolas.aula')),
            ],
            options={
                'permissions': [('view_relatorio_faltas', 'Pode visualizar o relatório de faltas')],
                'unique_together': {('aluno', 'aula')},
            },
        ),
    ]
