# Generated by Django 5.2.7 on 2025-11-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0007_aula_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/fotos/'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='status_matricula',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('transferido', 'Transferido'), ('cancelado', 'Cancelado'), ('concluido', 'Concluído'), ('trancado', 'Trancado')], default='ativo', max_length=20),
        ),
    ]
