# Generated by Django 5.2.7 on 2025-11-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0008_aluno_foto_aluno_status_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escolas.professor'),
        ),
    ]
