# Generated by Django 5.2.7 on 2025-11-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0010_historicoturmaaluno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_nascimento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estado_rg_pai',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf_certidao',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf_endereco',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf_rg',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
