# Generated by Django 5.2.7 on 2025-11-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0011_alter_aluno_estado_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estado_rg_mae',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
