# Generated by Django 5.2.7 on 2025-11-17 23:39

import escolas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0012_alter_aluno_estado_rg_mae'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='ano',
            field=models.IntegerField(default=escolas.models.ano_atual),
        ),
    ]
