# Generated by Django 5.2.7 on 2026-03-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolas', '0014_gradehoraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialetivo',
            name='cor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_letivo',
            field=models.IntegerField(default=2026),
        ),
    ]
